### ISSUE TITLE
Scripted stopped working (unknown reason)

### ISSUE THREAD

**Issue by Sjonnie2018** [DcR-NL/synology-vpn-reconnect#1]
Hi,

I have been using your script for some time now. It has worked flawlessly since the beginning but the last week (or two) it would not reconnect my openvpn connection to PIA. Reconnecting from the control panel of my Synology DS215+ works however.

Has something changed in the way Synology treats vpn connections? Is there some modification I can perform on the script to make it work again (scripting skills are close to zero ;))?

Looking foward!

Regards,

Sjonnie

Last part of the log file:
`'kill client ...OK
get arguemnt protocol: openvpn
get arguemnt name: PIA_OpenVPN
Reconnect [PIA_OpenVPN] ... failed
Retry(1)...failed
[INFO] VPN check: End
[INFO] VPN check: Start [2018-07-17 10:04:24 +02]
[INFO] VPN check: Running with user with sufficient privileges
[INFO] VPN check: Interface tun0 is up
[WARN] VPN check: Skipping IP check; no domain defined
[INFO] VPN check: VPN not allowed to connect to URL: https://www.cnbc.com/
[INFO] VPN check: VPN not allowed to connect to URL: https://www.nbc.com/
[INFO] VPN check: VPN not allowed to connect to URL: https://tweakers.net/
[WARN] VPN check: VPN needs to be reconnected. Cause: "Not allowed to connect to any of the specified URLs"

kill client ...OK`'

**Comment by Manfred73** [comment]
I've been using this script for some time and it seemed to work. But lately it doesn't reconnect properly anymore.
Before this script I used 1.0.0 script from Ian Harrier. But I've also tried the latest version 1.1.1 from Ian Harrier (https://github.com/ianharrier/synology-scripts), and that no longer works either on DSM 6.2.3-25426 Update 3.
Anyone any clue how to get one of these scripts working again? I've raised a support ticket with Synology also asking when they will finally implement a proper VPN connection and autoconnect option after all these years, but I'm not getting my hopes up on that one.

**Comment by BobWs** [comment]
Did you guys solved this problem?

**Comment by DcR-NL** [comment]
I'm sorry, haven't been using this script for many years now; completely moved to Docker. I recommend looking at [Gluetun](https://github.com/qdm12/gluetun) if you are able to run Docker. This way your VPN is handled with actual grace, and you are able to connect other containers so that they all use the same VPN connection. I'm using it in conjunction with [Deluge](https://hub.docker.com/r/linuxserver/deluge).
