### ISSUE TITLE
Telegram notification

### ISSUE THREAD

**Issue by BobWs** [DcR-NL/synology-vpn-reconnect#2]
Any chance you could add telegram api as a notification to your script? The log file is handy, but one still need to login in DSM to see the logs. Some kind of notification e.g. Telegram could help to quicker respond and spot VPN connection problems.

Thanks for the great script!

**Comment by DcR-NL** [comment]
Please look at my comment in https://github.com/DcR-NL/synology-vpn-reconnect/issues/1
